TARGET = plants_eaters_main
OBJS = plants_eaters_main.o entity.o gen_alg_game.o ../../bitset_genetics.o ../../chromosome.o
CFLAGS = -Wall -I. -I../../


$(TARGET): $(OBJS)
	g++  $(CFLAGS) $(OBJS) -o ../../$(TARGET)